[package]
name = "macros-rs"
version = "1.1.0"
edition = "2021"
license = "MIT"
description = "fluffy, simple & useful macros"
repository = "https://git.furry.win/crates/macros"

[dependencies]
termcolor = "1.4.1"
